services:
  - type: web
    name: cracktrack-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false        # paste your MongoDB Atlas connection string here
      - key: IGDB_CLIENT_ID
        sync: false
      - key: IGDB_CLIENT_SECRET
        sync: false
